- hosts: terraform-ansible
  tasks:
  - name: create index
    copy:
      dest: /home/ubuntu/index.html
      content: <h1>Meu nome nao e Jhonny</h1>
  - name: create server
    shell: "sudo nohup busybox httpd -f -p 8080 &"