- hosts: terraform-ansible
  tasks:
  - name: Install Python3 and Virtualenv
    apt:
      pkg:
      - python3
      - virtualenv
      update_cache: yes
    become: yes
  - name: Install pip dependencies (Django and Django Rest)
    pip:
      virtualenv: /home/ubuntu/test/venv
      name:
        - django
        - djangorestframework
  - name: Project Init
    shell: '. /home/ubuntu/test/venv/bin/activate; django-admin startproject setup /home/ubuntu/test/'
    ignore_erros: yes
  - name: Changing host settings
    lineinfile: 
      path: /home/ubuntu/test/setup/settings.py
      regexp: 'ALLOWED_HOSTS'
      line: 'ALLOWED_HOSTS = ["*"]'
      backrefs: yes
  